spring.application.name=career-assistant-backend

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:career_assistant}?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:database}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
openrouter.api.key=${OPENROUTER_API_KEY:}

server.port=8080